In [1]:
#import into the library
import numpy as np
import sys

# The basics

- It is a multi-deminsional array

- numpy uses fixed type 

- continuous memory

- SIMD Vector Processing (single instruction multiple data) & effective cache utilisation

- Plotting (Matplotlib)

- Backend (Pandas)

- Machine learning

In [2]:
#1d array
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
#2d array
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get dimension of an array

a.ndim

1

In [7]:
b.ndim

2

In [10]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
# How much memory

a.dtype

dtype('int64')

In [12]:
# change dtype 1d array
a = np.array([1,2,3], dtype='int32')

In [13]:
a.dtype

dtype('int32')

In [14]:
# Get size
a.itemsize

4

In [16]:
# Get total size
a.size * a.itemsize

12

In [17]:
a.nbytes

12

In [18]:
# Not for B

b.dtype

dtype('float64')

In [19]:
b.itemsize

8

# Access and change rows, columns etc.. in numpy

In [47]:
# 2X7 array
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a.shape

(2, 7)

In [22]:
# get specific element [r, c]
a[1, 5]

13

In [23]:
# Can also use negative notation 
a[1, -2]

13

In [24]:
# get specific row --> : will get everything in the row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
# get specific column --> to get 3 and 10
a[:, 2]

array([ 3, 10])

# complex skip

In [27]:
# More complex [startindex:endindex:stepsize]
#to get every other element

a[0, 1:6:2]

array([2, 4, 6])

In [29]:
# can also use the negative
a[0, 1:-1:2]

array([2, 4, 6])

In [30]:
# to change an element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [31]:
#to replace information in a column
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [32]:
#to replace information in a column with different numbers
a[:, 2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3d example

In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [35]:
# get specific element (work outside in)
b[0,1,1]

4

In [39]:
# replace - as long as it is the same dimension
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# initialise array types

In [42]:
# all 0s matrix
np.zeros((2,3,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [44]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [46]:
# any other number and make a float of it
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [49]:
# Any other number (full_like) - from a prev - make sure it is loaded in again.
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
#initialse matrix of random numbers - no need to pass in tuples
np.random.rand(4,2,3)

array([[[0.16012132, 0.40467626, 0.39916331],
        [0.14337999, 0.81638683, 0.88410225]],

       [[0.48185872, 0.69895266, 0.48528952],
        [0.68605049, 0.03064223, 0.48350707]],

       [[0.4287255 , 0.43786441, 0.91780004],
        [0.06265256, 0.41968929, 0.86419514]],

       [[0.7124437 , 0.64548823, 0.64562754],
        [0.30696396, 0.14761411, 0.97530807]]])

In [52]:
# to pass in a shape
np.random.random_sample(a.shape)

array([[0.25639327, 0.01300013, 0.90426269, 0.09817853, 0.90420618,
        0.59967688, 0.71819407],
       [0.37721949, 0.58268487, 0.91870645, 0.84171072, 0.49137425,
        0.91806979, 0.63893621]])

In [54]:
# random interger values - add in random number otherwise it will start from 0 and add in a shape otherwise 
#it will just be one number too. 7 is exclusive.
np.random.randint(7, size=(3,3))

array([[1, 4, 5],
       [5, 6, 4],
       [1, 1, 3]])

In [56]:
np.random.randint(-4,7, size=(3,3))

array([[-4,  5,  2],
       [ 5, -2,  0],
       [ 2,  5,  5]])

In [59]:
#identity matrix - square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
# repeat arrays

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [86]:
# challenge 

x = np.array([[1,1,1,1,1]])
r2 = np.repeat(x, 5, axis=0)
print(r2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [88]:
# change the numbers in the column 
r2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [103]:
r2[:, 1] = [1,0,0,0,1]
r2[:, 3] = [1,0,0,0,1]
r2[:, 2] = [1,0,9,0,1]
print(r2)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [105]:
# Another method

output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [106]:
z= np.zeros((3,3))
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [110]:
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [111]:
# or use -1 

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### becareful when copying arrays!

In [112]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [113]:
b = a
print(b)

[1 2 3]


In [115]:
b[0] = 100
print(b)

[100   2   3]


In [116]:
print(a)

[100   2   3]


### The a now also has the 100  as we said b points to where a is. 

In [119]:
#to prevent this 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathamatics

In [120]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [121]:
a + 2

array([3, 4, 5, 6])

In [122]:
a-2

array([-1,  0,  1,  2])

In [123]:
a * 2

array([2, 4, 6, 8])

In [124]:
a /2

array([0.5, 1. , 1.5, 2. ])

In [126]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [127]:
a ** 2

array([ 1,  4,  9, 16])

In [128]:
# take the sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [129]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear algebra

In [130]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [131]:
b = np.full((3,2), 2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [132]:
#3 cols and 3 rows
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [133]:
# matrix multiply function 

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [134]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# more information 

https://docs.scipy.org/doc/numpy/reference/routines.linglg.html

## Statistics

In [135]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
np.min(stats)

1

In [139]:
np.max(stats)

6

In [140]:
# gives min of first and second row
np.min(stats, axis=1)

array([1, 4])

In [141]:
# gives min of first row
np.min(stats, axis=0)

array([1, 2, 3])

In [143]:
np.sum(stats)#all elements

21

In [144]:
np.sum(stats, axis=0) #just first row

array([5, 7, 9])

## Reorganising arrays

In [145]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [150]:
print(before.shape)

(2, 4)


In [149]:
# reshape
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [152]:
# as long as there are the same amount of numbers 

after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Vertically stacking vectors

In [154]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

# horizonal stacks

In [156]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [157]:
h2

array([[0., 0.],
       [0., 0.]])

In [159]:
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

## Load data from file

In [176]:
data = np.genfromtxt('data/data.txt', delimiter=',')

In [163]:
data.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [164]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

### Boolean masking and advanced indexing

In [165]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [166]:
data[data > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [168]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])

In [169]:
a[[1,2,8]]

array([2, 3, 9])

In [170]:
np.any(data >50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [171]:
np.all(data >50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [173]:
#Will just give the rows
np.all(data >50, axis=1)

array([False, False, False])

In [178]:
print(data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [181]:
((data > 50) & (data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [182]:
(~((data > 50) & (data < 100))) #the reverse

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [183]:
# Testing question indexing part of the matrix
# a[2:4, 0:2]
# a[[0,1,2,3], [1,2,3,4]]
# a[[0,4,5],3:]

# Find index of value

In [184]:
# Create a numpy array from a list of numbers
arr = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [185]:
result = np.where(arr == 19)

In [186]:
print('Tuple of arrays returned : ', result)

Tuple of arrays returned :  (array([8]),)
